/***/
-- CC/PARAMETROS/MOTIVOS DE BLOQUEO
SELECT ccblqcblq, ccblqdesc FROM ccblq;
INSERT INTO ccblq (ccblqcblq,ccblqdesc) VALUES (1,'FALTA DE FONDOS                                                                                                         ');
INSERT INTO ccblq (ccblqcblq,ccblqdesc) VALUES (2,'INSUFIENCIA DE FONDOS                                                                                                   ');
INSERT INTO ccblq (ccblqcblq,ccblqdesc) VALUES (3,'HABILITACION DE CUENTA                                                                                                  ');
INSERT INTO ccblq (ccblqcblq,ccblqdesc) VALUES (4,'CIERRE DE CUENTA                                                                                                        ');
INSERT INTO ccblq (ccblqcblq,ccblqdesc) VALUES (5,'CUENTA CERRADA                                                                                                          ');
INSERT INTO ccblq (ccblqcblq,ccblqdesc) VALUES (6,'CUENTA CLAUSURADA                                                                                                       ');
INSERT INTO ccblq (ccblqcblq,ccblqdesc) VALUES (7,'BLOQUEO TEMPORAL DE CUENTA                                                                                              ');

-- CC/PARAMETROS/TIPOS DE CUENTAS CORRIENTES
SELECT ccccatpcc, ccccadesc, ccccacapb, ccccacapd, ccccaretb, ccccaretd, ccccauser, ccccahora, ccccafpro FROM cccca;
INSERT INTO cccca (ccccatpcc,ccccadesc,ccccacapb,ccccacapd,ccccaretb,ccccaretd,ccccauser,ccccahora,ccccafpro) VALUES (1,'PERSONAS NATURALES2                     ','22403130        ','22403230        ','22403130        ','22403230        ','AMY','14:59:19','2022-06-15');
INSERT INTO cccca (ccccatpcc,ccccadesc,ccccacapb,ccccacapd,ccccaretb,ccccaretd,ccccauser,ccccahora,ccccafpro) VALUES (2,'PRUEBAS                                 ','22403130        ','22403130        ','22403130        ','22403130        ','AMY','13:26:44','2022-06-14');

-- CC/Parametros/Mant. Cargos parametros
SELECT cccgpccrg, cccgpdesc, cccgptpcg, cccgpdias, cccgpttrn, cccgpfapl, cccgpbapl, cccgpfcob, cccgpcmon, cccgpmont, cccgpcctb, cccgpadic, cccgpmiva FROM cccgp;
INSERT INTO cccgp (cccgpccrg,cccgpdesc,cccgptpcg,cccgpdias,cccgpttrn,cccgpfapl,cccgpbapl,cccgpfcob,cccgpcmon,cccgpmont,cccgpcctb,cccgpadic,cccgpmiva) VALUES (1,'CARGO                         ',1,NULL,1,1,2,1,1,50000.000000,'21201101        ',NULL,'N');

-- CC/PARAMETROS/MANTENIMIENTO DE CONCEPTOS
SELECT * FROM cccon;
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,0,'TIPOS DE MOVIMIENTO                     ','     ',0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,1,'DEBITOS                                 ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,2,'CREDITOS                                ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,3,'TRASPASOS                               ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,6,'AVANCES                                 ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,7,'CAMBIOS DE ESTADO                       ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,8,'PIGNORACION DE FONDOS                   ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,10,'TRANSACCIONES ESPECIALES                ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,11,'PAGO DE CHEQUES SUCURSALES Y CORRESP.   ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,15,'TRANSACCIONES ELECTRON                  ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,16,'TRASACCIONES AVANCES                    ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,20,'INTERESES SOBREGIRO                     ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,21,'CARGOS SOBREGIRO                        ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,22,'GARANTIAS                               ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,23,'AVANCES CUENTAS CORRIENTES              ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,40,'DEBITO CON EMISION DE FACTURA           ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,50,'TRANSACCIONES CAJA                      ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,51,'TRANSACCIONES CAJA DE AHORRO            ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,52,'TRANSACCION SERVICIOS INSTITUCIONES     ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,53,'TRANSACCION BOLETAS DE GARANTIA         ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,54,'TRANSACCIONES AVALES BANCARIOS          ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,55,'TRANSACCION COBRANZA                    ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,56,'OPERACIONES ACREDITIVOS DE IMPORTACION  ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,57,'TRANSACCIONES DE GIROS                  ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,58,'TRANSACCION DE D.P.F.                   ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,59,'TRANSACCIONES DE CHEQUES DE GERENCIA    ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,63,'ADELANTO DE EFECTIVO TARJ.CREDITO       ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,64,'COBRO DE COMISIONES                     ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,70,'PRESTAMOS COMERCIALES                   ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,80,'TRANSFERENCIA A/DE OTROS BANCOS OFFICE  ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,85,'RECAUDACION/DEVOLUCION POR ACH          ','     ',0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (1,99,'TRASPASOS BANCA POR INTERNET            ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (2,0,'STATUS USO                              ','     ',0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (2,1,'TODO USO                                ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (2,2,'SOLO DEPOSITO                           ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (2,3,'SOLO RETIRO                             ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (3,0,'MANEJO                                  ','     ',0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (3,1,'INDIIVIDUAL                             ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (3,2,'CONJUNTA                                ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (3,3,'ALTERNA                                 ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (4,0,'STATUS DE LA CUENTA                     ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (4,1,'ACTIVA                                  ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (4,2,'INMOVILIZADA                            ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (4,3,'CLAUSURADA                              ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (4,4,'CERRADA                                 ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (4,5,'LIQUIDADA                               ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (4,6,'BLOQUEO TEMPORAL                        ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (5,0,'STATUS CHEQUES                          ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (5,1,'HABILITADO                              ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (5,2,'RESERVADO                               ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (5,3,'CERTIFICADO                             ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (5,4,'EXTRAVIADO O ROBADO                     ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (5,5,'RECHAZADO EN CAMARA                     ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (5,6,'CHEQUE CERTFICADO DEVUELTO              ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (5,7,'NO HABILITADO                           ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (5,8,'PAGADO                                  ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (5,9,'ANULADO                                 ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (6,0,'MOTIVOS RECHAZO DE CHEQUES              ','     ',0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (2,6,'1131                                    ',NULL,9);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (3,6,'132132123131313                         ',NULL,9);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (6,1,'RECHAZO POR FALTA DE FONDOS             ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (6,2,'RECHAZO POR CHEQUE MAL GIRADO           ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (6,3,'RECHAZO POR CHEQUE EN MAL ESTADO        ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (6,4,'RECHAZO POR FALTA DE FIRMAS             ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (6,5,'CUENTA CERRADA                          ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (6,6,'FALTA FIRMA DE ENDOSO                   ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (6,7,'NO CORRESPONDE A LA PLAZA               ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (6,8,'FECHA CADUCA                            ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (6,9,'RETENCION JUDICIAL                      ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (6,10,'ALTERACION DE DOCUMENTO                 ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (6,11,'FALTA DE SELLO DE CAMARA                ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (6,12,'FIRMA NO REGISTRADA DEL GIRADOR         ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (7,0,'VIA INGRESO DE CHEQUES                  ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (7,1,'PAGADO                                  ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (7,2,'CAMARA                                  ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (7,3,'DEPOSITO                                ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (8,0,'ESTADOS CARTERA                         ','     ',0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (8,1,'AUTORIZADO Y NO DESEMBOLSADO            ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (8,2,'VIGENTE                                 ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (8,3,'VIGENTE LARGO PLAZO                     ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (8,4,'ATRASADO                                ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (8,5,'VENCIDO                                 ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (8,6,'EJECUCION                               ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (8,7,'CASTIGO                                 ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (8,9,'CANCELADO                               ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (9,0,'TIPOS DE DEPOSITOS                      ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (9,1,'EFECTIVO                                ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (9,2,'CHEQUES AJENOS                          ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (9,3,'CHEQUES PROPIOS                         ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (9,4,'CHEQUES AJENOS FUERA DE HORA            ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (10,0,'TIPOS DE AVANCE                         ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (10,1,'AVANCES CONTRATADOS                     ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (10,2,'AVANCES EVENTUALES                      ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (11,0,'TIPOS DE RESPONSABILIDAD                ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (11,1,'RESPONSABILIDAD DIRECTA                 ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (11,2,'RESPONSABILIDAD INDIRECTA               ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (12,0,'TIPOS DE CARGOS                         ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (12,1,'CARGOS GENERALES                        ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (12,2,'CARGOS PENALES                          ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (12,3,'CARGOS JUDICIALES                       ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (12,4,'CARGOS ESPECIALES                       ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (12,5,'CARGOS GENERALES PERSONAL NATURAL       ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (12,6,'CARGOS PENALES CORRIENTES               ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (12,8,'CARGOS PENALES ANTERIORES               ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (13,0,'FACTORES DE APLICACION                  ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (13,1,'MONTO FIJO                              ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (13,2,'PORCENTAJE                              ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (13,3,'PORCENTAJE EN RELACION AL TIEMPO        ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (13,4,'PORCENTAJE DESDE LA ULTIMA TRANSACCION  ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (14,0,'BASE DE APLICACION                      ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (14,2,'SOBRE EL SALDO DEL CREDITO              ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (15,0,'FORMAS DE COBRO                         ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (15,1,'UNA SOLA VEZ                            ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (15,2,'EN CADA OPERACION                       ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (16,0,'TIPOS DE TRANSACCION CARTERA            ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (16,1,'DESEMBOLSO                              ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (16,2,'PAGO                                    ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (17,0,'TIPOS DE CAPITALIZACION                 ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (17,1,'PROMEDIO MENSUAL - ABONO FIN DE MES     ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (17,2,'CAPITALIZACION DIARIA - ABONO DIARIO    ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (18,0,'TIPOS DE TASA                           ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (18,1,'TASA EN BASE A RANGOS                   ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (18,2,'TASA FIJA                               ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (20,0,'VALORES CARTERA                         ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (20,1,'CAPITAL                                 ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (20,2,'INTERES                                 ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (21,0,'TIPOS GLOSA EXTRACTO                    ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (21,1,'BANCO                                   ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (21,2,'casilla interna                         ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (21,3,'casilla externa                         ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (21,4,'Domicilio                               ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (21,5,'Agencia                                 ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (22,0,'TIPOS DE CHEQUE                         ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (22,1,'NORMAL                                  ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (22,2,'VISADO                                  ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (22,3,'GERENCIA                                ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (30,0,'MOTIVO DE APERTURA                      ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (30,1,'prueba 1                                ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (30,2,'PAGO DE HABERES / JUBILACION            ','PHJ  ',0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (30,3,'PAGO DE EXPENSAS                        ','PDE  ',0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (30,4,'ADMINISTRACION DE CREDITOS              ','ADC  ',0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (30,5,'ADMINISTRACION DE RECURSOS              ','ADR  ',0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (30,6,'GIROS Y REMESAS                         ','GYR  ',0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (30,7,'GARANTIAS                               ','GAR  ',0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (51,0,'CAMBIOS DE ESTADO                       ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (51,1,'CAMBIO DE TIPO DE CUENTA                ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (3,4,'NUEVO MANEJO                            ','NM   ',0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (2,4,'NUEVO USO                               ','D    ',0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (3,5,'PRUEBA                                  ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (2,5,'PRUEBA                                  ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (6,13,'CUENTA CLAUSURADA                       ',NULL,0);
INSERT INTO cccon (ccconpref,ccconcorr,cccondesc,ccconabre,ccconmrcb) VALUES (6,14,'POR ORDEN DE NO PAGO                    ',NULL,0);

-- CC/PARAMETROS/MANTENIMIENTO CONCEPTOS - PREF 6 -> GLOSA
SELECT ccglopref, ccglocorr, ccgloglos FROM ccglo;
INSERT INTO ccglo (ccglopref,ccglocorr,ccgloglos) VALUES (6,1,'PRUEBA                                                                                                                                                ');
INSERT INTO ccglo (ccglopref,ccglocorr,ccgloglos) VALUES (6,2,'PRUEBA 2                                                                                                                                              ');
INSERT INTO ccglo (ccglopref,ccglocorr,ccgloglos) VALUES (6,3,'PRUEBA 3                                                                                                                                              ');
INSERT INTO ccglo (ccglopref,ccglocorr,ccgloglos) VALUES (6,4,'PRUEBA 4                                                                                                                                              ');
INSERT INTO ccglo (ccglopref,ccglocorr,ccgloglos) VALUES (6,5,'                                                                                                                                                      ');
INSERT INTO ccglo (ccglopref,ccglocorr,ccgloglos) VALUES (6,6,'                                                                                                                                                      ');
INSERT INTO ccglo (ccglopref,ccglocorr,ccgloglos) VALUES (6,7,'                                                                                                                                                      ');
INSERT INTO ccglo (ccglopref,ccglocorr,ccgloglos) VALUES (6,8,'                                                                                                                                                      ');
INSERT INTO ccglo (ccglopref,ccglocorr,ccgloglos) VALUES (6,9,'                                                                                                                                                      ');
INSERT INTO ccglo (ccglopref,ccglocorr,ccgloglos) VALUES (6,10,'                                                                                                                                                      ');
INSERT INTO ccglo (ccglopref,ccglocorr,ccgloglos) VALUES (6,11,'                                                                                                                                                      ');
INSERT INTO ccglo (ccglopref,ccglocorr,ccgloglos) VALUES (6,12,'                                                                                                                                                      ');
INSERT INTO ccglo (ccglopref,ccglocorr,ccgloglos) VALUES (6,13,'                                                                                                                                                      ');
INSERT INTO ccglo (ccglopref,ccglocorr,ccgloglos) VALUES (6,14,'                                                                                                                                                      ');

-- CC/PARAMETROS/TIPOS DE CUENTAS CORRIENTES
SELECT cctcctpcc, cctccdesc, cctccctab, cctccctad, cctccctsb, cctccctsd, cctccctcb, cctccctcd, cctccavib, cctccavid, cctccavmb, cctccavmd, cctcctmcb, cctcctmcd, cctcctcap, cctccsmib, cctccsmid, cctccctau, cctccctsu, cctccctcu, cctccimab, cctccimad, cctcctpgr, cctccctrb, cctccctrd, cctccctru FROM cctcc;
INSERT INTO cctcc (cctcctpcc,cctccdesc,cctccctab,cctccctad,cctccctsb,cctccctsd,cctccctcb,cctccctcd,cctccavib,cctccavid,cctccavmb,cctccavmd,cctcctmcb,cctcctmcd,cctcctcap,cctccsmib,cctccsmid,cctccctau,cctccctsu,cctccctcu,cctccimab,cctccimad,cctcctpgr,cctccctrb,cctccctrd,cctccctru) VALUES (1,'PERSONAS NATURALES2                     ','21101130        ','21101230        ','22102130        ','22102230        ','22403130        ','22403230        ',0.00,10.00,0.00,30.00,0.000,40.000,2,0.00,20.00,NULL,NULL,NULL,0.00,0.00,30,'21401130        ','21401230        ',NULL);
INSERT INTO cctcc (cctcctpcc,cctccdesc,cctccctab,cctccctad,cctccctsb,cctccctsd,cctccctcb,cctccctcd,cctccavib,cctccavid,cctccavmb,cctccavmd,cctcctmcb,cctcctmcd,cctcctcap,cctccsmib,cctccsmid,cctccctau,cctccctsu,cctccctcu,cctccimab,cctccimad,cctcctpgr,cctccctrb,cctccctrd,cctccctru) VALUES (2,'PRUEBAS                                 ','22403130        ','22403130        ','22403130        ','22403130        ','22403130        ','22403130        ',0.00,0.00,0.00,0.00,0.000,0.000,1,0.00,0.00,NULL,NULL,NULL,0.00,0.00,30,'22403130        ','22403130        ',NULL);

-- TIPOS DE CHEQUERAS
SELECT cctchcant, cctchcmon, cctchdesc, cctchimpt FROM cctch;
INSERT INTO cctch (cctchcant,cctchcmon,cctchdesc,cctchimpt) VALUES (1,1,'PRUEBA TIPO CHEQUERA          ',2000.00);
INSERT INTO cctch (cctchcant,cctchcmon,cctchdesc,cctchimpt) VALUES (25,1,'CHEQUERA DE 25 CHEQUES M.N.   ',60.00);
INSERT INTO cctch (cctchcant,cctchcmon,cctchdesc,cctchimpt) VALUES (25,2,'CHEQUERAS DE 25 CHEQUES M.E.  ',10.00);
INSERT INTO cctch (cctchcant,cctchcmon,cctchdesc,cctchimpt) VALUES (50,1,'CHEQUERAS DE 50 CHEQUES M.N.  ',120.00);
INSERT INTO cctch (cctchcant,cctchcmon,cctchdesc,cctchimpt) VALUES (50,2,'CHEQUERAS DE 50 CHEQUES M.E.  ',20.00);
INSERT INTO cctch (cctchcant,cctchcmon,cctchdesc,cctchimpt) VALUES (152,1,'CHEQUERAS DE 152 CHEQUES M.N. ',350.00);

-- TIPOS DE MOVIMIENTO
SELECT cctmvpref, cctmvcorr, cctmvdesc, cctmvctbl, cctmvadic
FROM cctmv
ORDER BY 1,2;

INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (1,5,'RETENCIONES JUDICIALES CUENTAS CORRIENTE','21401M04        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (1,20,'CARGO POR DIFERENCIA DE CAMBIO          ','54201201        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (1,43,'COMISIONES ACH                          ','54105M12        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (1,44,'DEBITOS P/OPERACIONES COMEX             ','18307M11        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (1,45,'DEBITOS P/OPERERACIONES TARJ.CREDITO    ','18307M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (1,48,'OPERACIONES CONTAB.PUENTE               ','18307M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (1,52,'COBRO IVA                               ','24203101        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (1,58,'REMESAS/GIROS BCOS.EXTERIOR             ','18307M11        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (1,59,'COBRO ITF                               ','24203103        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (1,60,'TRANSFERENCIAS ACH                      ','24405M12        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (1,63,'TELECEL BXI                             ','24405M11        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (1,65,'TRANSF.BANCA X INTERNET                 ','24405M11        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (1,67,'NUEVATEL BXI                            ','24405M11        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (1,68,'ENTEL BXI                               ','24405M11        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (1,71,'DEV.NAL.SEG.VIDA Y SALUD                ','24405M18        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (1,72,'DEV.NAL.SEG.INCENDIO Y ALIADOS          ','24405M19        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (1,73,'DEP.GTIA.P/EMISION BOLETA GTIA.         ','18307M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,1,'TRANSF. CAJEROS ENLACE                  ','18307M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,2,'REVERSION CHQ. VISADO PROPIO            ','18307M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,3,'LIBERACION RET. JUDICIAL CTAS. CTES.    ','21401M04        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,20,'DEVOLUCION POR CARGO SOBREGIRO          ','18307M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,21,'DEVOLUCION POR CARGO FORMULARIOS        ','54501M01        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,22,'DEVOLUCION POR CARGO VENTA CHEQUERAS    ','54501M03        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,23,'DEVOLUCION POR CARGO ADM.CTAS.CTES.     ','54103M01        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,24,'ABONO POR DIFERENCIA DE CAMBIO          ','54201201        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,43,'ABONO POR OPERACIONES CARTERA           ','18307M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,44,'ABONO POR OPERACIONES COMEX             ','18307M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,45,'ABONO POR OPER. TARJ. DE CREDITO        ','18307M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,46,'ABONO POR GIROS INTERIOR                ','18307M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,47,'ABONO POR GIROS EXTERIOR                ','18307M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,48,'ABONO POR OPERERACIONES CONTABILIDAD    ','18307M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,51,'DEVOLUCION IVA                          ','24203101        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,52,'INTERESES GANADOS CC COOP.INCAHUASI     ','41301M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,53,'REMESAS/GIROS BEC                       ','18307M07        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,54,'REMESAS/GIROS BGA                       ','18307M08        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,55,'REMESAS/GIROS BUN                       ','18307M09        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,56,'TARJETA DE CREDITO ADICIONAL            ','54115M08        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,57,'REMESAS/GIROS BCOS.EXTERIOR             ','18307M11        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,58,'SERVICIOS BANCA P/INTERNET              ','24405M11        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,60,'TRANSFERENCIAS ACH                      ','24405M12        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,63,'TELECEL BXI                             ','24405M11        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,64,'NACIONAL SEGUROS VIDA Y SALUD           ','24405M18        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,65,'NACIONAL SEGUROS INCENDIO Y ALIADOS     ','24405M19        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,67,'NUEVATEL BXI                            ','24405M03        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,68,'ENTEL BXI                               ','24405M03        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,69,'DEVOLUCION ITF                          ','24203103        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,70,'DEV.DEP.GTIA.P/EMISION BOLETA GTIA.     ','18307M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (2,71,'OP.PENDIENTE 1                          ','18307M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (3,1,'TRASPASO ENTRE CUENTAS CORRIENTES       ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (3,2,'TRASPASO ENTRE CTA.CTE. - CTA.AHORRO    ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (3,3,'TRASPASO CUENTAS CORRIENTES PROPIAS-BXI ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (3,4,'TRASPASO CTA.CTE.-CTA.AHORRO PROPIAS-BXI',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (3,5,'TRASPASO CUENTA CORRIENTE AJENA-BXI     ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (3,6,'TRASPASO CTA.AHORRO-CTA.CTE.AJENA-BXI   ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (6,1,'ABONO POR SOBREGIRO CT.                 ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (6,2,'ABONO POR SOBREGIRO EV.                 ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (6,3,'CARGO POR SOBREGIRO CT.                 ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (6,4,'CARGO POR SOBREGIRO EV.                 ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (7,1,'CAMBIOS DE ESTADO                       ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (7,2,'CAMBIO DE ESTADO AVANCES                ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (10,1,'INTERESES GANADOS                       ','41101M01        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (10,2,'RETENCION DE IMPUESTOS IVA              ','24203101        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (10,3,'CARGO POR VENTA DE CHEQUERA             ','54501M03        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (10,4,'CERTIFICACION DE CHEQUE                 ','21105M01        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (10,5,'PAGO DE CHEQUES CAMARA P/BANCO          ','18307M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (10,6,'LIBERACION DE DEPOSITOS CHQ/AJENOS      ','21104M01        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (10,7,'CARGO MANTENIMIENTO CUENTA              ','54103M01        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (10,8,'RECHAZO CHQS CAMARA                     ','18307M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (10,9,'ANULACION CHQ.CERTIFICADO               ','21105M01        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (10,11,'CTAS.CTES.INMOV.POR PRESCRIPCION        ','22111M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (10,15,'CARGO MTTO. CUENTA REZAGADOS            ','54103M01        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (10,20,'TRANSFERENCIA A TERCEROS                ','24199101        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (10,21,'ABONO TRASFERENCIA ACH                  ','24199101        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (11,3,'CHEQUE PAGADO SUC. LA PAZ               ','18308M01        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (11,4,'CHEQUE PAGADO SUC. SCZ.                 ','18308M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (11,5,'CHEQUE PAGADO SUC. CBBA.                ','18308M03        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (11,11,'REVERSION CHEQUE VISADO                 ','18307117        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,1,'DEBITO POR RETIRO ATM-PROPIO            ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,2,'DEBITO POR RETIRO POS-PROPIO            ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,3,'DEBITO POR COMPRA P.O.S-PROPIO          ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,4,'DEBITO POR RETIRO ATM-VISA              ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,5,'DEBITO POR RETIRO POS-VISA              ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,6,'DEBITO POR COMPRA P.O.S-VISA            ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,7,'DEBITO POR RETIRO ATM-RED               ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,8,'DEBITO POR RETIRO ATM-REDBANK           ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,9,'DEBITO POR TRANSAC.NO FINANC.           ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,12,'CGO.X NO DISP. O POR LIMITE             ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,13,'TRANSACCIONES SMS                       ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,20,'CGO.X RET.EFEC. ATM-PROPIO              ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,21,'CGO.X RET.EFEC. POS-PROPIO              ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,22,'CGO.X COMPRA P.O.S-PROPIO               ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,23,'CGO.X RET.EFEC. ATM-VISA                ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,24,'CGO.X RET.EFEC. POS-VISA                ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,25,'CGO.X COMPRA P.O.S-VISA                 ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,26,'CGO.X RET.EFEC. ATM-RED                 ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,27,'CGO.X RET.EFEC. ATM-REDBANK             ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,28,'CGO.X TRANS.NO FINANCIERAS              ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,29,'CGO.X TRANS.SMS                         ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (15,54,'PAGO MINIMO DE TARJETA DE CREDITO       ','18307125        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (16,1,'DEVOL.POR RETIRO ATM-PROPIO             ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (16,2,'DEVOL.POR RETIRO POS-PROPIO             ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (16,3,'DEVOL.POR COMPRA P.O.S-PROPIO           ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (16,4,'DEVOL.POR RETIRO ATM-VISA               ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (16,5,'DEVOL.POR RETIRO POS-VISA               ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (16,6,'DEVOL.POR COMPRA P.O.S-VISA             ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (16,7,'DEVOL.POR RETIRO ATM-RED                ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (16,8,'DEVOL.POR RETIRO ATM-REDBANK            ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (16,13,'REVERSION TRANSACCIONES SMS             ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (16,20,'DEVOL.CGO.RET.EFEC. ATM-PROPIO          ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (16,21,'DEVOL.CGO.RET.EFEC. POS-PROPIO          ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (16,22,'DEVOL.CGO.COMPRA P.O.S-PROPIO           ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (16,23,'DEVOL.CGO.RET.EFEC. ATM-VISA            ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (16,24,'DEVOL.CGO.RET.EFEC. POS-VISA            ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (16,25,'DEVOL.CGO.COMPRA P.O.S-VISA             ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (16,26,'DEVOL.CGO.RET.EFEC. ATM-RED             ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (16,27,'DEVOL.CGO.RET.EFEC. ATM-REDBANK         ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (16,28,'DEVOL.CGO.TRANS.NO FINANCIERAS          ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (20,2,'INTERESES SOBREGIRO                     ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (21,1,'CARGO                                   ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (21,2,'REHAB. CUENTA CLAUSURADA                ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (21,3,'PENALES DE 1 A 30 DIAS                  ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (21,4,'PENALES DE 31 A 60 DIAS                 ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (21,5,'PENALES DE 61 A 90 DIAS                 ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (21,6,'PENALES MAYORES A 90 DIAS               ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (21,10,'GASTOS JUDICIALES M/N                   ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (21,16,'COMISION SOBREGIRO EVENTUAL             ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (21,17,'CERTIFICACION DE CHEQUES M.N.           ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (21,18,'EMISION CHQ. DE GERENCIA M.N.           ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (21,19,'EMIS.CHQ. DE GERENCIA M.E.              ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (21,97,'SEGURO DE VIDA                          ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,1,'CARGO MANT.CUENTA                       ','54105M16        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,2,'COMIS.P/GIROS EXTERIOR                  ','54105M01        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,3,'COMIS.TRASPASOS/EMISION CHEQUES         ','54105M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,4,'COMIS.P/RECHAZO CHEQUE                  ','54105M10        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,5,'COMIS.EMISION CHEQUE DE GERENCIA        ','54105M13        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,6,'COMIS.CHEQUES CERTIFICADOS              ','54107M01        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,7,'COMIS.EMISION RESUMEN TARJ.CREDITO      ','54115102        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,8,'COMIS.MANTENIM.CUENTA TARJ.CREDITO      ','54115103        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,9,'COMIS.REPOSICION TARJETA CREDITO        ','54115104        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,10,'COMIS.REPOSICION PIN TARJETA CREDITO    ','54115105        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,11,'COMIS.INCREM.TEMPORAL TARJETA CREDITO   ','54115106        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,12,'COMIS.P/SOBREGIRO TARJETA DE CREDITO    ','54115107        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,13,'COMIS.TARJETA CREDITO ADICIONAL         ','54115108        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,14,'COMIS.AVANCE EFECTIVO                   ','54115124        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,15,'COMISIONES VARIAS                       ','54199M01        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,16,'COMIS.P/COBRO SERVICIOS                 ','54199M02        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,17,'COMIS.P/COBRO SERV.COLEGIOS             ','54199M04        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,18,'COMIS.P/AP.LINEA CREDITO                ','54199M06        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,19,'REPOS.FORM.P/DESMB./AMORTZ.MN           ','54501M01        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,20,'VENTA CHEQUERA                          ','54501M03        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,21,'REHAB. CUENTA CLAUSURADA                ','54505M13        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,22,'ALQUILER CAJAS DE SEGURIDAD             ','54503M01        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,23,'ING.SERVICIOS ADICIONALES               ','54505M01        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,24,'INGRESOS P/FULL SERVICE                 ','54505102        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,25,'INGRESO POR FOTOCOPIAS                  ','54505M04        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,26,'CERTIFICACIONES Y LEGALIZACIONES        ','54505M06        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,27,'EMISION ESTADO DE CUENTA                ','54505M08        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,28,'TARJETA DE DEBITO                       ','54505M09        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,29,'HABILITACION CTA.CTE.                   ','54505M13        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,30,'DEVOL.CHEQUES SIN FONDOS (CAJAS)        ','54505M14        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,31,'COMIS.EMISION BOLETA GARANTIA           ','51901M01        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,32,'COMIS.RE-EMISION BOLETA GARANTIS        ','54199M01        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,33,'COMIS.LIP                               ','54105M11        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (40,34,'COMISION ACH                            ','54105M12        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (50,1,'DEPOSITO DE EFECTIVO                    ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (50,2,'PAGO DE CHEQUES                         ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (50,3,'DEPOSITO CHEQUES OTROS BANCOS LOCALES   ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (50,4,'DEPOSITO CHEQUES DEL MISMO BANCO        ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (50,20,'IMPTO. A LAS TRANSACC.(ITF)             ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (50,21,'REV.IMPTO. A LAS TRANSACC.(ITF)         ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (51,20,'IMPTO. A LAS TRANSACC.(ITF)             ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (51,21,'*REV* ITF                               ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (52,1,'FACTURACION A TERCEROS                  ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (53,1,'COBROS POR CARGOS DE BOLETAS            ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (53,2,'PAGOS DE BOLETAS DE GARANTIAS           ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (53,3,'COBRANZA DE CREDITOS BOLETAS DE GARANTIA',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (53,6,'PREPAGO DE BOLETA                       ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (54,1,'COBROS POR CARGOS DE AVALES BANCARIOS   ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (54,2,'PAGO DE AVALES BANCARIOS                ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (54,3,'COBRANZA DE CREDITO AVALES BANCARIOS    ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (55,1,'COBRANZA DOCUMENTOS                     ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (55,2,'LIQUIDACION DOCUMENTOS                  ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (56,1,'OPERACIONES ACREDITIVOS DE IMPORTACION  ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (56,2,'OPERACIONES ACREDITIVOS (CREDITOS)      ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (57,1,'DEBITO POR ENVIO DE GIRO                ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (57,2,'ABONO POR GIRO RECIBIDO                 ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (57,4,'ABONO POR GIRO RECIBIDO EXT.            ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (58,1,'APERTURA DE D.P.F.                      ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (58,2,'LIQUIDACION DE CAPITAL E INTERES D.P.F. ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (58,3,'LIQUIDACION DE INTERES D.P.F.           ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (58,4,'AUMENTO DE CAPITAL D.P.F.               ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (58,5,'DISMINUCION DE CAPITAL D.P.F.           ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (58,6,'ABONO AUTOM. DE INTERES                 ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (59,1,'DEBITO POR EMISION CHQ.GERENCIA         ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (59,2,'ABONO POR DEPOSITO CHQ.GERENCIA         ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (61,1,'DESEMB.DOC.DESC.                        ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (61,2,'COBRO DOC.DESC                          ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (64,1,'CARGO P/EXTRACTO CTAS.CTES.             ','54505M08        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (64,2,'COMISION CERTIF. DE CHEQUES             ','54107M01        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (64,3,'CARGO P/ EXTRACTO CAJA DE AHORROS       ','54505M08        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (64,4,'COMISION EMISION CHQ.GERENCIA           ','54105M13        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (64,5,'COMISION RETIRO MENOR A 100             ','54103M04        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (64,6,'COMIS.DEPOSITOS P/CONFIRMAR             ','54103M04        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (64,8,'COMIS.CHQS.RECHAZADOS                   ','54105M10        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (64,9,'COMIS.AVANCE CONTRATADO                 ','54103M04        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (64,10,'COMIS.AVANCE EVENTUAL                   ','54103M04        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (64,11,'COMIS.BLOQUEO DE CUENTA                 ','54103M04        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (64,12,'COMIS.ANULACION DE CHEQUE               ','54105M10        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (64,13,'COMIS.HABILITACION DE CUENTA            ','54103M04        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (64,14,'COMIS.HABILITAC.DE CHEQUE               ','54105M10        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (64,15,'COMIS.INMOVILIZ.DE CUENTA               ','54103M04        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (64,18,'CARGO.EMISION TARJ.DEBITO               ','54505M09        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (64,19,'COMIS.TARJ.ADICIONALES                  ','54505M09        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (64,20,'COMIS.RENOVA.TARJETA                    ','54505M09        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (64,21,'COMIS.BLOQ/HABIL.DE TARJETA             ','54505M09        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (64,30,'COMIS.INSUFICIENCIA DE FONDOS           ','54103M04        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (64,51,'CARGO  EXTRACTO RECHAZO DE CEQUES       ','54505M08        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (66,1,'DEBITO REVERSION REMESA FAMILIAR        ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (66,2,'ABONO REMESA FAMILIAR                   ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (70,0,'PRESTAMOS COMERCIALES                   ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (70,1,'DESEMBOLSO DE PRESTAMOS                 ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (70,2,'COBRO DE PRESTAMO                       ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (70,3,'DESMBOLSO PREeSTAMOS CAJA               ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (70,4,'COBRO EFECTIVO                          ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (70,5,'DEBITO ATUOMATICO(PRESTAMOS)            ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (70,6,'DEBITO AUTOMATICO(SOLUZIONA)            ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (71,1,'DESEMBOLSO PREST. DE CONSUMO            ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (71,2,'COBRO PREST.DE CONSUMO                  ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (80,1,'TRANSF. BANCO MERCANTIL                S','11201101        ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (81,1,'PAGO DE COBRANZA EN ADMINISTRACION      ',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (81,2,'ABONO POR ADELANTO EN TARJETA DE CREDITO',NULL,NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (85,0,'RECAUDACION/DEVOLUCION POR ACH          ',NULL,0);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (85,1,'INGRESO COMISION ACH                    ','                ',0);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (85,2,'EGRESO COMISION ACH                     ',NULL,0);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (85,3,'PREDESEMBOLSO PRESTAMO ACH              ',NULL,0);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (85,4,'DEVOLUCION DE EXCEDENTE                 ',NULL,0);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (99,1,'TRASPASOS CC-CC BANCA POR INTERNET      ','                ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (99,2,'TRASPASOS CC-CA BANCA POR INTERNET      ','                ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (99,3,'PAGO PLANILLA AFP                       ','                ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (99,4,'PAGO BOA                                ','                ',NULL);
INSERT INTO cctmv (cctmvpref,cctmvcorr,cctmvdesc,cctmvctbl,cctmvadic) VALUES (99,5,'PAGO DE IMPUESTO                        ',NULL,NULL);

SELECT cctpgcpig, cctpgdesc, cctpgcmon, cctpgctbz, cctpgctbl, cctpgtpgr FROM cctpg;
INSERT INTO cctpg (cctpgcpig,cctpgdesc,cctpgcmon,cctpgctbz,cctpgctbl,cctpgtpgr) VALUES (50,'RETENCION JUDICIAL PERSONA NATURAL      ',1,'S','21401130',30);
INSERT INTO cctpg (cctpgcpig,cctpgdesc,cctpgcmon,cctpgctbz,cctpgctbl,cctpgtpgr) VALUES (40,'MONTO MINIMO                            ',1,'N',NULL,30);
-- Mant. Parametros Generales
SELECT ccctlndoc, ccctlncta, ccctlfulp, ccctlnmes, ccctldpsm, ccctlcdpc, ccctlcadc, ccctlcdif, ccctlctra, ccctlfulc, ccctlfanc, ccctlfucm, ccctlfacm, ccctlntra, ccctltasb, ccctltasd, ccctltano, ccctlctgd, ccctlctga, ccctlcpvg, ccctlcpvn, ccctlcpv2, ccctlcpej, ccctlpdvg, ccctlpdvn, ccctlpdv2, ccctlpdej, ccctlipvg, ccctlipvn, ccctlipv2, ccctlipej, ccctlsdvg, ccctlsdvn, ccctlsdv2, ccctlsdej, ccctlsavg, ccctlsavn, ccctlsav2, ccctlsaej, ccctldeje, ccctlfcia, ccctlfcie, ccctlfucp, ccctlfacp, ccctlpeja, ccctlvfir, ccctlccas, ccctlpcas, ccctlicas, ccctlsdca, ccctlsaca, ccctlkrec, ccctlkare, ccctliccg, ccctliacg, ccctltcvp, ccctlnser FROM ccctl;
INSERT INTO ccctl (ccctlndoc,ccctlncta,ccctlfulp,ccctlnmes,ccctldpsm,ccctlcdpc,ccctlcadc,ccctlcdif,ccctlctra,ccctlfulc,ccctlfanc,ccctlfucm,ccctlfacm,ccctlntra,ccctltasb,ccctltasd,ccctltano,ccctlctgd,ccctlctga,ccctlcpvg,ccctlcpvn,ccctlcpv2,ccctlcpej,ccctlpdvg,ccctlpdvn,ccctlpdv2,ccctlpdej,ccctlipvg,ccctlipvn,ccctlipv2,ccctlipej,ccctlsdvg,ccctlsdvn,ccctlsdv2,ccctlsdej,ccctlsavg,ccctlsavn,ccctlsav2,ccctlsaej,ccctldeje,ccctlfcia,ccctlfcie,ccctlfucp,ccctlfacp,ccctlpeja,ccctlvfir,ccctlccas,ccctlpcas,ccctlicas,ccctlsdca,ccctlsaca,ccctlkrec,ccctlkare,ccctliccg,ccctliacg,ccctltcvp,ccctlnser) VALUES (504234,3,'1993-12-31',NULL,730,'24201M01        ','21104M01        ','54201M01        ',NULL,'2021-02-28','2021-02-28','2021-09-30','2005-08-31',326280,24.000,24.000,360,'64101M01        ','74101M01        ','13102M01        ','13102M01        ','13302M01        ','13402M01        ','13801M26        ','13801M26        ','13803M26        ','13804M26        ','51302M01        ','51302M01        ','51501M26        ','51601M26        ','86601M26        ','86601M26        ','86603M26        ','86604M26        ','96601M26        ','96601M26        ','96601M26        ','96601M26        ',90,'2021-02-28','2021-02-27',NULL,NULL,'N','N','13904M01        ','43401M01        ','43401M01        ','86501M02        ','96501M02        ','53101M02        ',NULL,'53102M02        ',NULL,0.00050,4);
