SELECT *
FROM fecon
ORDER BY 1,2

insert into fecon values( 1,0 , 'ESTADOS FACTURACION ELECTRONICA', '', 0);
insert into fecon values( 1, 100, 'PENDIENTE DE ENVIO','', 0);
insert into fecon values( 1, 101, 'ENVIADA AL FEEL', '', 0);
insert into fecon values( 1, 102, 'PROCESADA CORRECTAMENTE', '', 0);
insert into fecon values( 1, 103, 'ERROR', '', 0);
insert into fecon values( 1, 200, 'PENDIENTE DE ANULAR', '', 0);
insert into fecon values( 1, 201, 'SOLICITUD DE ANULACION ENVIADA AL FEEL', '', 0);
insert into fecon values( 1 , 202, 'ANULACION PROCESADA', '', 0);
insert into fecon values( 1 , 204, 'ANULACION CON ERROR', '', 0);
insert into fecon values( 1 , 400, 'FACTURA VALIDA', '', 0);
insert into fecon values( 1 , 401, 'FACTURA OBSERVADA ver fehfeslme y fehfesler', '', 0);
insert into fecon values( 2 , 0, 'CODIGO DE ERRORES', 'ERROR', 0);
insert into fecon values(2, 300, 'ERROR DE FORMATO', '1200', 0);
insert into fecon values(3, 0, 'ESTADOS CONSULTA DOCUMENTO FISCAL (A FEEL) - fehfeecdf','', 0);
insert into fecon values(3, 500, 'PENDIENTE DE CONSULTA', '', 0);
insert into fecon values(3, 501, 'ENVIADA A FEEL', '', 0);
insert into fecon values(3, 502, 'RESPUESTA CONSULTA CON ERROR FEEL', '', 0);
insert into fecon values(3, 503, 'ACTUALIZADA', '', 0);
insert into fecon values(4, 0, 'PARAMETROS SIN', '', 0);
insert into fecon values(4, 2,'TIPO_DOCUMENTO_SECTOR', '', 0);
insert into fecon values(4, 3,'INVOICE_LEGEND', '', 0);
insert into fecon values(4, 4,'MOTIVO_ANULACION', '', 0);
insert into fecon values(4, 5,'PAIS_ORIGEN', '', 0);
insert into fecon values(4, 6,'TIPO_DOCUMENTO_IDENTIDAD', '', 0);
insert into fecon values(4, 7,'TIPO_EMISION', '', 0);
insert into fecon values(4, 8,'TIPO_HABITACION', '', 0);
insert into fecon values(4, 9,'METODO_PAGO', '', 0);
insert into fecon values(4, 10,'TIPO_MONEDA', '', 0);
insert into fecon values(4, 11,'TIPO_PUNTO_VENTA', '', 0);
insert into fecon values(4, 12,'TIPO_FACTURA', '', 0);
insert into fecon values(4, 13,'UNIDAD_MEDIDA', '', 0);
INSERT INTO fecon VALUES(5,0,"MOT. ANULACION DE FACTURA","",0);
INSERT INTO fecon VALUES(5,1,"FACTURA MAL EMITIDA","",0);
INSERT INTO fecon VALUES(5,2,"DATOS DE EMISION INCORRECTOS","",0);
INSERT INTO fecon VALUES(5,3,"FACTURA O NOTA DE CREDITO-DEBITO DEVUELTA","",0);

SELECT *
FROM ipcon
WHERE ipconpref = 100
ORDER BY 1,2

INSERT INTO ipcon VALUES(100,0,"TIPO DOCUMENTO FISCAL",NULL);
INSERT INTO ipcon VALUES(100,1,"FACTURA CON DERECHO A C/F",NULL);
INSERT INTO ipcon VALUES(100,2,"FACTURA SIN DERECHO A C/F",NULL);
INSERT INTO ipcon VALUES(100,3,"DOCUMENTO DE AJUSTE",NULL);

SELECT *
FROM fedse
ORDER BY 1

INSERT INTO fedse VALUES(1,"FACTURA DE COMPRA Y VENTA",1,"FACTURA","CON DERECHO A CREDITO FISCAL",1,1);
INSERT INTO fedse VALUES(2,"FACTURA DE ALQUILER",1,"FACTURA DE ALQUILER","CON DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(3,"FACTURA COMERCIAL DE EXPORTACION",1,"FACTURA COMERCIAL DE EXPORTACION","SIN DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(4,"FACTURA COMERCIAL DE EXPORTACION LIBRE CONSIGNACION",1,"FACTURA COMERCIAL DE EXPORTACION LIBRE CONSIGNACION","SIN DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(5,"FACTURA DE VENTA DE ZONA FRANCA",1,"FACTURA DE VENTA DE ZONA FRANCA","SIN DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(6,"FACTURA DE SERVICIO TURISTICO Y HOSPEDAJE",1,"FACTURA DE SERVICIO TURISTICO Y HOSPEDAJE","SIN DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(7,"FACTURA DE SEGURIDAD ALIMENTARIA Y ABASTECIMIENTO",1,"FACTURA DE SEGURIDAD ALIMENTARIA Y ABASTECIMIENTO","SIN DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(8,"FACTURA TASA CERO VENTA DE LIBROS",1,"FACTURA TASA CERO VENTA DE LIBROS","SIN DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(9,"FACTURA TASA CERO DE TRANSACCIONES DE CARGA INTERNACIONAL",1,"FACTURA TASA CERO DE TRANSACCIONES DE CARGA INTERNACIONAL","SIN DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(10,"FACTURA DE COMPRA Y VENTA DE MONEDA EXTRANJERA",1,"FACTURA DE COMPRA Y VENTA DE MONEDA EXTRANJERA","SIN DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(11,"FACTURA DUTTY FREE",1,"FACTURA DUTTY FREE","SIN DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(12,"FACTURA SECTORES EDUCATIVOS",1,"FACTURA","CON DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(13,"FACTURA DE COMERCIALIZACION DE HIDROCARBUROS",1,"FACTURA","CON DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(14,"FACTURA DE SERVICIOS BASICOS",1,"FACTURA","CON DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(15,"FACTURA PRODUCTOS ALCANZADOS POR EL ICE",1,"FACTURA","CON DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(16,"FACTURA DE ENTIDADES FINANCIERAS",1,"FACTURA","CON DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(17,"FACTURA DE HOTELES",1,"FACTURA","CON DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(18,"FACTURA HOSPITALES/CLINICAS",1,"FACTURA","CON DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(19,"FACTURA DE JUEGOS DE AZAR",1,"FACTURA","CON DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(20,"FACTURA DE HIDROCARBUROS",1,"FACTURA","CON DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(21,"FACTURA COMERCIAL DE EXPORTACION DE MINERALES",1,"FACTURA","CON DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(22,"FACTURA DE VENTA DE MINERALES",1,"FACTURA","CON DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(23,"FACTURA DE TELECOMUNICACIONES",1,"FACTURA","CON DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(24,"FACTURA PREVALORADA",1,"FACTURA","CON DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(25,"NOTA DE CREDITO - DEBITO",1,"FACTURA","CON DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(26,"FACTURA COMERCIAL DE EXPORTACION DE SERVICIOS",1,"FACTURA","CON DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(27,"NOTA DE CONCILIACION",1,"FACTURA","CON DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(28,"BOLETO AEREO",1,"FACTURA","CON DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(29,"FACTURA DE SUMINISTRO DE ENERGIA",1,"FACTURA","CON DERECHO A CREDITO FISCAL",1,0);
INSERT INTO fedse VALUES(30,"FACTURA DE HIDROCARBUROS",1,"FACTURA","CON DERECHO A CREDITO FISCAL",1,0);

SELECT *
FROM fevdf
ORDER BY 1

INSERT INTO fevdf VALUES (1,"ACTIVIDAD ECONOMICA ",620100);
INSERT INTO fevdf VALUES (4,"MOTIVO DE ANULACION DE FACTURA ",1);
INSERT INTO fevdf VALUES (9,"FORMA DE PAGO ",1);
INSERT INTO fevdf VALUES (13,"UNIDAD DE MEDIDA",58);
INSERT INTO fevdf VALUES (20,"CODIGO DE SISTEMA","SIST-01");

SELECT *
FROM fesrl

-- MONITOR DE FACTURAS
SELECT *FROM fesrl
INSERT INTO fesrl VALUES('fetem',1);

SELECT *
FROM admdt
WHERE admdtmodn = 96

INSERT INTO admdt( admdtmodn, admdtmprn , admdtmdtn, admdtdesc, admdtnprg, admdtnimg, admdtstat, admdttama, admdtlibr, admdtnpnb)
VALUES(96, 2, 14, 'Monitor de Facturas', '', NULL, '1', 6, NULL, 'PHP/fec001.html'); 

--Config Monitor de facturas
--https://bankingly.lapromotora.com.bo/nb600/inc/configfe.html
