-- CONCEPTOS
SELECT *
FROM tacop 
ORDER BY 1,2

-- TARJETAS CREDITO REGLAS
SELECT *
FROM TAREG

-- BARRIO
SELECT *
FROM gbubn;

-- TC/ADMIN. RECEPCION DATOS - ATC/ARCH. MOVIMIENTOS EMISOR v. 6.0.7 - 1.0.1
SELECT *
FROM tcqrm;